[tox]
envlist = ty, py3.{13,14}

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    pytest
    pytest-xdist
commands =
    pytest

[testenv:ty]
passenv =
    TY_OUTPUT_FORMAT
deps =
    ty
    pytest
commands =
    ty check
