#include "amici/symbolic_functions.h"
#include "amici/defines.h"
#include "sundials/sundials_types.h"

#include <gsl/gsl-lite.hpp>
#include <algorithm>

#include "x.h"
#include "p.h"
#include "w.h"
#include "tcl.h"
#include "dtcldp.h"
#include "dwdp.h"

namespace amici {
namespace model_icg_sd {

void dwdp_icg_sd(realtype *dwdp, const realtype t, const realtype *x, const realtype *p, const realtype *k, const realtype *h, const realtype *w, const realtype *tcl, const realtype *dtcldp){
    dBSA_dBW = 0.013049716999999997*std::pow(BW, -0.46220000000000006)*std::pow(HEIGHT, 0.39639999999999997);  // dwdp[0]
    dCO_dBW = COBW*f_cardiac_output;  // dwdp[1]
    dVar_dBW = (1 - HCT)*(-FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVar);  // dwdp[2]
    dVbi_dBW = FVbi;  // dwdp[3]
    dVgi_dBW = FVgi;  // dwdp[4]
    dVhv_dBW = (1 - HCT)*(-FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVhv);  // dwdp[5]
    dVli_dBW = FVli*(1 - resection_rate);  // dwdp[6]
    dVlu_dBW = FVlu;  // dwdp[7]
    dVpo_dBW = (1 - HCT)*(-FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVpo);  // dwdp[8]
    dVve_dBW = (1 - HCT)*(-FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVve);  // dwdp[9]
    dAar_icg_dBW = Car_icg*(1 - HCT)*(-FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVar);  // dwdp[10]
    dAhv_icg_dBW = Chv_icg*(1 - HCT)*(-FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVhv);  // dwdp[11]
    dApo_icg_dBW = Cpo_icg*(1 - HCT)*(-FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVpo);  // dwdp[12]
    dAve_icg_dBW = Cve_icg*(1 - HCT)*(-FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVve);  // dwdp[13]
    dVgi_plasma_dBW = FVgi*Fblood*(1 - HCT);  // dwdp[14]
    dVgi_tissue_dBW = FVgi*(1 - Fblood);  // dwdp[15]
    dVli_plasma_dBW = FVli*Fblood*(1 - HCT)*(1 - resection_rate);  // dwdp[16]
    dVli_tissue_dBW = FVli*(1 - Fblood)*(1 - f_tissue_loss)*(1 - resection_rate);  // dwdp[17]
    dVlu_plasma_dBW = FVlu*Fblood*(1 - HCT);  // dwdp[18]
    dVlu_tissue_dBW = FVlu*(1 - Fblood);  // dwdp[19]
    dVre_dBW = FVre;  // dwdp[20]
    dMar_icg_dBW = -Aar_icg*Mr_icg*(-FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVar)/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2));  // dwdp[21]
    dMhv_icg_dBW = -Ahv_icg*Mr_icg*(-FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVhv)/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2));  // dwdp[22]
    dMpo_icg_dBW = -Apo_icg*Mr_icg*(-FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVpo)/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2));  // dwdp[23]
    dMve_icg_dBW = -Ave_icg*Mr_icg*(-FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + FVve)/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2));  // dwdp[24]
    dVre_plasma_dBW = FVre*Fblood*(1 - HCT);  // dwdp[25]
    dVre_tissue_dBW = FVre*(1 - Fblood);  // dwdp[26]
    dBSA_dHEIGHT = 0.0096186459999999981*std::pow(BW, 0.53779999999999994)*std::pow(HEIGHT, -0.60360000000000003);  // dwdp[27]
    dCO_dCOBW = BW*f_cardiac_output;  // dwdp[28]
    dVar_dFblood = -BW*FVar*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[29]
    dVhv_dFblood = -BW*FVhv*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[30]
    dVpo_dFblood = -BW*FVpo*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[31]
    dVve_dFblood = -BW*FVve*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[32]
    dAar_icg_dFblood = -BW*Car_icg*FVar*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[33]
    dAhv_icg_dFblood = -BW*Chv_icg*FVhv*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[34]
    dApo_icg_dFblood = -BW*Cpo_icg*FVpo*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[35]
    dAve_icg_dFblood = -BW*Cve_icg*FVve*(1 - HCT)*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve);  // dwdp[36]
    dVgi_plasma_dFblood = BW*FVgi*(1 - HCT);  // dwdp[37]
    dVgi_tissue_dFblood = -BW*FVgi;  // dwdp[38]
    dVli_plasma_dFblood = BW*FVli*(1 - HCT)*(1 - resection_rate);  // dwdp[39]
    dVli_tissue_dFblood = -BW*FVli*(1 - f_tissue_loss)*(1 - resection_rate);  // dwdp[40]
    dVlu_plasma_dFblood = BW*FVlu*(1 - HCT);  // dwdp[41]
    dVlu_tissue_dFblood = -BW*FVlu;  // dwdp[42]
    dAgi_plasma_icg_dFblood = Cgi_plasma_icg*Vgi*(1 - HCT);  // dwdp[43]
    dAli_plasma_icg_dFblood = Cli_plasma_icg*Vli*(1 - HCT);  // dwdp[44]
    dAlu_plasma_icg_dFblood = Clu_plasma_icg*Vlu*(1 - HCT);  // dwdp[45]
    dMar_icg_dFblood = Aar_icg*BW*FVar*Mr_icg*(-FVar - FVhv - FVpo - FVve + 1)/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2)*(FVar + FVhv + FVpo + FVve));  // dwdp[46]
    dMhv_icg_dFblood = Ahv_icg*BW*FVhv*Mr_icg*(-FVar - FVhv - FVpo - FVve + 1)/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2)*(FVar + FVhv + FVpo + FVve));  // dwdp[47]
    dMpo_icg_dFblood = Apo_icg*BW*FVpo*Mr_icg*(-FVar - FVhv - FVpo - FVve + 1)/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2)*(FVar + FVhv + FVpo + FVve));  // dwdp[48]
    dMve_icg_dFblood = Ave_icg*BW*FVve*Mr_icg*(-FVar - FVhv - FVpo - FVve + 1)/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2)*(FVar + FVhv + FVpo + FVve));  // dwdp[49]
    dVre_plasma_dFblood = BW*FVre*(1 - HCT);  // dwdp[50]
    dVre_tissue_dFblood = -BW*FVre;  // dwdp[51]
    dAre_plasma_icg_dFblood = Cre_plasma_icg*Vre*(1 - HCT);  // dwdp[52]
    dMgi_plasma_icg_dFblood = -Agi_plasma_icg*Mr_icg/(std::pow(Fblood, 2)*Vgi*(1 - HCT));  // dwdp[53]
    dMli_plasma_icg_dFblood = -Ali_plasma_icg*Mr_icg/(std::pow(Fblood, 2)*Vli*(1 - HCT));  // dwdp[54]
    dMlu_plasma_icg_dFblood = -Alu_plasma_icg*Mr_icg/(std::pow(Fblood, 2)*Vlu*(1 - HCT));  // dwdp[55]
    dMre_plasma_icg_dFblood = -Are_plasma_icg*Mr_icg/(std::pow(Fblood, 2)*Vre*(1 - HCT));  // dwdp[56]
    dflux_LI__ICGIM_dFblood = -Cli_plasma_icg*LI__ICGIM_Vmax*LI__f_oatp1b3*Vli*(1 - f_tissue_loss)/(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil));  // dwdp[57]
    dflux_LI__ICGLI2CA_dFblood = -LI__ICGLI2CA_Vmax*LI__icg*Vli*(1 - f_tissue_loss)/(LI__ICGLI2CA_Km + LI__icg);  // dwdp[58]
    dflux_LI__ICGLI2BI_dFblood = -LI__ICGLI2BI_Vmax*LI__icg_bi*Vli*(1 - f_tissue_loss);  // dwdp[59]
    dVar_dHCT = BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) - BW*FVar;  // dwdp[60]
    dVhv_dHCT = BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) - BW*FVhv;  // dwdp[61]
    dVpo_dHCT = BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) - BW*FVpo;  // dwdp[62]
    dVve_dHCT = BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) - BW*FVve;  // dwdp[63]
    dAar_icg_dHCT = -Car_icg*(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar);  // dwdp[64]
    dAhv_icg_dHCT = -Chv_icg*(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv);  // dwdp[65]
    dApo_icg_dHCT = -Cpo_icg*(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo);  // dwdp[66]
    dAve_icg_dHCT = -Cve_icg*(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve);  // dwdp[67]
    dVgi_plasma_dHCT = -BW*FVgi*Fblood;  // dwdp[68]
    dVli_plasma_dHCT = -BW*FVli*Fblood*(1 - resection_rate);  // dwdp[69]
    dVlu_plasma_dHCT = -BW*FVlu*Fblood;  // dwdp[70]
    dAgi_plasma_icg_dHCT = -Cgi_plasma_icg*Fblood*Vgi;  // dwdp[71]
    dAli_plasma_icg_dHCT = -Cli_plasma_icg*Fblood*Vli;  // dwdp[72]
    dAlu_plasma_icg_dHCT = -Clu_plasma_icg*Fblood*Vlu;  // dwdp[73]
    dMar_icg_dHCT = Aar_icg*Mr_icg/(std::pow(1 - HCT, 2)*(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar));  // dwdp[74]
    dMhv_icg_dHCT = Ahv_icg*Mr_icg/(std::pow(1 - HCT, 2)*(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv));  // dwdp[75]
    dMpo_icg_dHCT = Apo_icg*Mr_icg/(std::pow(1 - HCT, 2)*(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo));  // dwdp[76]
    dMve_icg_dHCT = Ave_icg*Mr_icg/(std::pow(1 - HCT, 2)*(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve));  // dwdp[77]
    dVre_plasma_dHCT = -BW*FVre*Fblood;  // dwdp[78]
    dAre_plasma_icg_dHCT = -Cre_plasma_icg*Fblood*Vre;  // dwdp[79]
    dMgi_plasma_icg_dHCT = Agi_plasma_icg*Mr_icg/(Fblood*Vgi*std::pow(1 - HCT, 2));  // dwdp[80]
    dMli_plasma_icg_dHCT = Ali_plasma_icg*Mr_icg/(Fblood*Vli*std::pow(1 - HCT, 2));  // dwdp[81]
    dMlu_plasma_icg_dHCT = Alu_plasma_icg*Mr_icg/(Fblood*Vlu*std::pow(1 - HCT, 2));  // dwdp[82]
    dMre_plasma_icg_dHCT = Are_plasma_icg*Mr_icg/(Fblood*Vre*std::pow(1 - HCT, 2));  // dwdp[83]
    dFVre_dFVgi = -1;  // dwdp[84]
    dVgi_dFVgi = BW;  // dwdp[85]
    dVgi_plasma_dFVgi = BW*Fblood*(1 - HCT);  // dwdp[86]
    dVgi_tissue_dFVgi = BW*(1 - Fblood);  // dwdp[87]
    dFVre_dFVbi = -1;  // dwdp[88]
    dVbi_dFVbi = BW;  // dwdp[89]
    dFVre_dFVli = -1;  // dwdp[90]
    dVli_dFVli = BW*(1 - resection_rate);  // dwdp[91]
    dVli_plasma_dFVli = BW*Fblood*(1 - HCT)*(1 - resection_rate);  // dwdp[92]
    dVli_tissue_dFVli = BW*(1 - Fblood)*(1 - f_tissue_loss)*(1 - resection_rate);  // dwdp[93]
    dFVre_dFVlu = -1;  // dwdp[94]
    dVlu_dFVlu = BW;  // dwdp[95]
    dVlu_plasma_dFVlu = BW*Fblood*(1 - HCT);  // dwdp[96]
    dVlu_tissue_dFVlu = BW*(1 - Fblood);  // dwdp[97]
    dFVre_dFVve = -1;  // dwdp[98]
    dVar_dFVve = (1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[99]
    dVhv_dFVve = (1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[100]
    dVpo_dFVve = (1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[101]
    dVve_dFVve = (1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[102]
    dAar_icg_dFVve = Car_icg*(1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[103]
    dAhv_icg_dFVve = Chv_icg*(1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[104]
    dApo_icg_dFVve = Cpo_icg*(1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[105]
    dAve_icg_dFVve = Cve_icg*(1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[106]
    dMar_icg_dFVve = -Aar_icg*Mr_icg*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2));  // dwdp[107]
    dMhv_icg_dFVve = -Ahv_icg*Mr_icg*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2));  // dwdp[108]
    dMpo_icg_dFVve = -Apo_icg*Mr_icg*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2));  // dwdp[109]
    dMve_icg_dFVve = -Ave_icg*Mr_icg*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW)/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2));  // dwdp[110]
    dFVre_dFVar = -1;  // dwdp[111]
    dVar_dFVar = (1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[112]
    dVhv_dFVar = (1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[113]
    dVpo_dFVar = (1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[114]
    dVve_dFVar = (1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[115]
    dAar_icg_dFVar = Car_icg*(1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[116]
    dAhv_icg_dFVar = Chv_icg*(1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[117]
    dApo_icg_dFVar = Cpo_icg*(1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[118]
    dAve_icg_dFVar = Cve_icg*(1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[119]
    dMar_icg_dFVar = -Aar_icg*Mr_icg*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW)/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2));  // dwdp[120]
    dMhv_icg_dFVar = -Ahv_icg*Mr_icg*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2));  // dwdp[121]
    dMpo_icg_dFVar = -Apo_icg*Mr_icg*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2));  // dwdp[122]
    dMve_icg_dFVar = -Ave_icg*Mr_icg*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2));  // dwdp[123]
    dFVre_dFVpo = -1;  // dwdp[124]
    dVar_dFVpo = (1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[125]
    dVhv_dFVpo = (1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[126]
    dVpo_dFVpo = (1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[127]
    dVve_dFVpo = (1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[128]
    dAar_icg_dFVpo = Car_icg*(1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[129]
    dAhv_icg_dFVpo = Chv_icg*(1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[130]
    dApo_icg_dFVpo = Cpo_icg*(1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[131]
    dAve_icg_dFVpo = Cve_icg*(1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[132]
    dMar_icg_dFVpo = -Aar_icg*Mr_icg*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2));  // dwdp[133]
    dMhv_icg_dFVpo = -Ahv_icg*Mr_icg*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2));  // dwdp[134]
    dMpo_icg_dFVpo = -Apo_icg*Mr_icg*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW)/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2));  // dwdp[135]
    dMve_icg_dFVpo = -Ave_icg*Mr_icg*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2));  // dwdp[136]
    dFVre_dFVhv = -1;  // dwdp[137]
    dVar_dFVhv = (1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[138]
    dVhv_dFVhv = (1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[139]
    dVpo_dFVhv = (1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[140]
    dVve_dFVhv = (1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[141]
    dAar_icg_dFVhv = Car_icg*(1 - HCT)*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[142]
    dAhv_icg_dFVhv = Chv_icg*(1 - HCT)*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW);  // dwdp[143]
    dApo_icg_dFVhv = Cpo_icg*(1 - HCT)*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[144]
    dAve_icg_dFVhv = Cve_icg*(1 - HCT)*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2));  // dwdp[145]
    dMar_icg_dFVhv = -Aar_icg*Mr_icg*(BW*FVar*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar, 2));  // dwdp[146]
    dMhv_icg_dFVhv = -Ahv_icg*Mr_icg*(BW*FVhv*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2) - BW*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW)/((1 - HCT)*std::pow(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv, 2));  // dwdp[147]
    dMpo_icg_dFVhv = -Apo_icg*Mr_icg*(BW*FVpo*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo, 2));  // dwdp[148]
    dMve_icg_dFVhv = -Ave_icg*Mr_icg*(BW*FVve*Fblood/(FVar + FVhv + FVpo + FVve) + BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/std::pow(FVar + FVhv + FVpo + FVve, 2))/((1 - HCT)*std::pow(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve, 2));  // dwdp[149]
    dQgi_dFQgi = QC*f_bloodflow;  // dwdp[150]
    dQh_dFQh = QC*f_bloodflow*f_exercise;  // dwdp[151]
    dQlu_dFQlu = QC;  // dwdp[152]
    dflux_Flow_arli_li_icg_df_shunts = -Car_icg*Qha;  // dwdp[153]
    dflux_Flow_arli_hv_icg_df_shunts = Car_icg*Qha;  // dwdp[154]
    dflux_Flow_po_li_icg_df_shunts = -Cpo_icg*Qpo;  // dwdp[155]
    dflux_Flow_po_hv_icg_df_shunts = Cpo_icg*Qpo;  // dwdp[156]
    dflux_Flow_li_hv_icg_df_shunts = -Cli_plasma_icg*(Qha + Qpo);  // dwdp[157]
    dVli_tissue_df_tissue_loss = -BW*FVli*(1 - Fblood)*(1 - resection_rate);  // dwdp[158]
    dflux_LI__ICGIM_df_tissue_loss = -Cli_plasma_icg*LI__ICGIM_Vmax*LI__f_oatp1b3*Vli*(1 - Fblood)/(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil));  // dwdp[159]
    dflux_LI__ICGLI2CA_df_tissue_loss = -LI__ICGLI2CA_Vmax*LI__icg*Vli*(1 - Fblood)/(LI__ICGLI2CA_Km + LI__icg);  // dwdp[160]
    dflux_LI__ICGLI2BI_df_tissue_loss = -LI__ICGLI2BI_Vmax*LI__icg_bi*Vli*(1 - Fblood);  // dwdp[161]
    dQgi_df_bloodflow = FQgi*QC;  // dwdp[162]
    dQh_df_bloodflow = FQh*QC*f_exercise;  // dwdp[163]
    dCO_df_cardiac_output = BW*COBW;  // dwdp[164]
    dQh_df_exercise = FQh*QC*f_bloodflow;  // dwdp[165]
    dVli_dresection_rate = -BW*FVli;  // dwdp[166]
    dVli_plasma_dresection_rate = -BW*FVli*Fblood*(1 - HCT);  // dwdp[167]
    dVli_tissue_dresection_rate = -BW*FVli*(1 - Fblood)*(1 - f_tissue_loss);  // dwdp[168]
    dCLinfusion_icg_dMr_icg = -Ri_icg/(std::pow(Mr_icg, 2)*(Cve_icg + 9.9999999999999998e-13));  // dwdp[169]
    dMar_icg_dMr_icg = Aar_icg/((1 - HCT)*(-BW*FVar*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVar));  // dwdp[170]
    dMhv_icg_dMr_icg = Ahv_icg/((1 - HCT)*(-BW*FVhv*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVhv));  // dwdp[171]
    dMpo_icg_dMr_icg = Apo_icg/((1 - HCT)*(-BW*FVpo*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVpo));  // dwdp[172]
    dMve_icg_dMr_icg = Ave_icg/((1 - HCT)*(-BW*FVve*Fblood*(-FVar - FVhv - FVpo - FVve + 1)/(FVar + FVhv + FVpo + FVve) + BW*FVve));  // dwdp[173]
    dXar_icg_dMr_icg = Aar_icg;  // dwdp[174]
    dXhv_icg_dMr_icg = Ahv_icg;  // dwdp[175]
    dXpo_icg_dMr_icg = Apo_icg;  // dwdp[176]
    dXve_icg_dMr_icg = Ave_icg;  // dwdp[177]
    dMgi_plasma_icg_dMr_icg = Agi_plasma_icg/(Fblood*Vgi*(1 - HCT));  // dwdp[178]
    dMli_plasma_icg_dMr_icg = Ali_plasma_icg/(Fblood*Vli*(1 - HCT));  // dwdp[179]
    dMlu_plasma_icg_dMr_icg = Alu_plasma_icg/(Fblood*Vlu*(1 - HCT));  // dwdp[180]
    dXgi_plasma_icg_dMr_icg = Agi_plasma_icg;  // dwdp[181]
    dXli_plasma_icg_dMr_icg = Ali_plasma_icg;  // dwdp[182]
    dXlu_plasma_icg_dMr_icg = Alu_plasma_icg;  // dwdp[183]
    dMre_plasma_icg_dMr_icg = Are_plasma_icg/(Fblood*Vre*(1 - HCT));  // dwdp[184]
    dXre_plasma_icg_dMr_icg = Are_plasma_icg;  // dwdp[185]
    dflux_iv_icg_dMr_icg = -IVDOSE_icg*Ki_icg/std::pow(Mr_icg, 2);  // dwdp[186]
    dKi_icg_dti_icg = -41.579999999999998/std::pow(ti_icg, 2);  // dwdp[187]
    dCLinfusion_icg_dRi_icg = 1/(Mr_icg*(Cve_icg + 9.9999999999999998e-13));  // dwdp[188]
    dflux_LI__ICGIM_dLI__ICGIM_Vmax = Cli_plasma_icg*LI__f_oatp1b3*Vli*(1 - Fblood)*(1 - f_tissue_loss)/(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil));  // dwdp[189]
    dflux_LI__ICGIM_dLI__ICGIM_Km = -Cli_plasma_icg*LI__ICGIM_Vmax*LI__f_oatp1b3*Vli*(1 - Fblood)*(1 - f_tissue_loss)*(1 + LI__bil_ext/LI__ICGIM_ki_bil)/std::pow(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil), 2);  // dwdp[190]
    dflux_LI__ICGIM_dLI__ICGIM_ki_bil = Cli_plasma_icg*LI__ICGIM_Km*LI__ICGIM_Vmax*LI__bil_ext*LI__f_oatp1b3*Vli*(1 - Fblood)*(1 - f_tissue_loss)/(std::pow(LI__ICGIM_ki_bil, 2)*std::pow(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil), 2));  // dwdp[191]
    dflux_LI__ICGIM_dLI__f_oatp1b3 = Cli_plasma_icg*LI__ICGIM_Vmax*Vli*(1 - Fblood)*(1 - f_tissue_loss)/(Cli_plasma_icg + LI__ICGIM_Km*(1 + LI__bil_ext/LI__ICGIM_ki_bil));  // dwdp[192]
    dflux_LI__ICGLI2CA_dLI__ICGLI2CA_Vmax = LI__icg*Vli*(1 - Fblood)*(1 - f_tissue_loss)/(LI__ICGLI2CA_Km + LI__icg);  // dwdp[193]
    dflux_LI__ICGLI2CA_dLI__ICGLI2CA_Km = -LI__ICGLI2CA_Vmax*LI__icg*Vli*(1 - Fblood)*(1 - f_tissue_loss)/std::pow(LI__ICGLI2CA_Km + LI__icg, 2);  // dwdp[194]
    dflux_LI__ICGLI2BI_dLI__ICGLI2BI_Vmax = LI__icg_bi*Vli*(1 - Fblood)*(1 - f_tissue_loss);  // dwdp[195]
}

} // namespace model_icg_sd
} // namespace amici
