# Function reference {.doc .doc-index}

## Sensitivity

Functionality related to sensitivity and uncertainty analysis.

| | |
| --- | --- |
| [sensitivity](sensitivity.qmd#sbmlsim.sensitivity) | Sensitivity analysis. |
| [sensitivity.sensitivity_local](sensitivity.sensitivity_local.qmd#sbmlsim.sensitivity.sensitivity_local) | Local sensitivity analysis using finite differences. |
| [sensitivity.sensitivity_fast](sensitivity.sensitivity_fast.qmd#sbmlsim.sensitivity.sensitivity_fast) | Global sensitivity analysis using FAST (Fourier Amplitude Sensitivity Test). |
| [sensitivity.sensitivity_sobol](sensitivity.sensitivity_sobol.qmd#sbmlsim.sensitivity.sensitivity_sobol) | Global sensitivity analysis using Sobol indices. |
| [sensitivity.sensitivity_morris](sensitivity.sensitivity_morris.qmd#sbmlsim.sensitivity.sensitivity_morris) | Morris sensitivity analysis. |
| [sensitivity.sensitivity_sampling](sensitivity.sensitivity_sampling.qmd#sbmlsim.sensitivity.sensitivity_sampling) | Sampling-based sensitivity and uncertainty analysis. |
| [sensitivity.classification](sensitivity.classification.qmd#sbmlsim.sensitivity.classification) | Classification of sensitivities and uncertainties. |

## Parameter optimization

Functionality related to parameter optimization.

| | |
| --- | --- |
| [fit](fit.qmd#sbmlsim.fit) | Package for parameter fitting and parameter optimization. |
