# sensitivity.classification { #sbmlsim.sensitivity.classification }

`sensitivity.classification`

Classification of sensitivities and uncertainties.

## Classes

| Name | Description |
| --- | --- |
| [SensitivityClassification](#sbmlsim.sensitivity.classification.SensitivityClassification) | Sensitivity classification. |
| [UncertaintyClassification](#sbmlsim.sensitivity.classification.UncertaintyClassification) | Uncertainty classification. |

### SensitivityClassification { #sbmlsim.sensitivity.classification.SensitivityClassification }

```python
sensitivity.classification.SensitivityClassification()
```

Sensitivity classification.

### UncertaintyClassification { #sbmlsim.sensitivity.classification.UncertaintyClassification }

```python
sensitivity.classification.UncertaintyClassification()
```

Uncertainty classification.

## Functions

| Name | Description |
| --- | --- |
| [sensitivity_classification](#sbmlsim.sensitivity.classification.sensitivity_classification) | Classification of local sensitivity as per WHO IPCS guidance. |
| [sensitivity_classification_symbol](#sbmlsim.sensitivity.classification.sensitivity_classification_symbol) | Calculates symbol for sensitivity classification. |
| [uncertainty_classification](#sbmlsim.sensitivity.classification.uncertainty_classification) | Classification of uncertainty as per WHO IPCS guidance. |

### sensitivity_classification { #sbmlsim.sensitivity.classification.sensitivity_classification }

```python
sensitivity.classification.sensitivity_classification(s)
```

Classification of local sensitivity as per WHO IPCS guidance.

Classification based on absolute sensitivity:

- High: `|Si,j| >= 0.5`
- Medium: `0.2 <= |Si,j| < 0.5`
- Low: `0.1 <= |Si,j| < 0.2`
- Negligible: `|Si,j| < 0.1`

#### References {.doc-section .doc-section-references}

International Programme on Chemical Safety (IPCS). Characterization and
application of physiologically based pharmacokinetic models in risk assessment.
World Health Organization; 2010. Contract No.: 9.

### sensitivity_classification_symbol { #sbmlsim.sensitivity.classification.sensitivity_classification_symbol }

```python
sensitivity.classification.sensitivity_classification_symbol(s)
```

Calculates symbol for sensitivity classification.

### uncertainty_classification { #sbmlsim.sensitivity.classification.uncertainty_classification }

```python
sensitivity.classification.uncertainty_classification(u)
```

Classification of uncertainty as per WHO IPCS guidance.

- High: `Ui,j >= 2`
- Medium: `0.3 <= |Ui,j| < 2`
- Low: `0 <= |Ui,j| < 0.3`

#### References {.doc-section .doc-section-references}

International Programme on Chemical Safety (IPCS). Characterization and application of physiologically based pharmacokinetic models in risk assessment.
World Health Organization; 2010. Contract No.: 9.
