project:
  type: website
  output-dir: ../_site

  render:
    - "*.qmd"
    - "*.md"
    - "!tests/"
    - "!release-notes/"
    - "!src/"

website:
  title: "sbmlsim"
  "description": "SBML simulation made easy"
  favicon: images/favicon/favicon.ico
  site-url: https://matthiaskoenig.github.io/sbmlsim
  open-graph: true
  page-navigation: true
  bread-crumbs: true
  repo-url: https://github.com/matthiaskoenig/sbmlsim
  repo-branch: develop
  repo-link-target: _blank
  repo-actions: [ edit, source, issue ]
  sidebar:
    # title: sbmlsim
    # logo: images/favicon/sbmlsim-100x100-300dpi.png
    style: "docked"
    type: "dark"
    search: true
    contents:
       - index.qmd
       - section: "Analysis"
         contents:
          - text: Sensitivity Analysis
            href: sensitivity.qmd
       - section: "API"
         contents:
          - text: "Sensitivity"
            href: api/index.qmd
          - text: "`sensitivity`"
            href: api/sensitivity.qmd
          - text: "`sensitivity_fast`"
            href: api/sensitivity.sensitivity_fast.qmd
          - text: "`sensitivity_local`"
            href: api/sensitivity.sensitivity_local.qmd
          - text: "`sensitivity_morris`"
            href: api/sensitivity.sensitivity_morris.qmd
          - text: "`sensitivity_sobol`"
            href: api/sensitivity.sensitivity_sobol.qmd
          - text: "`sensitivity_sampling`"
            href: api/sensitivity.sensitivity_sampling.qmd

    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/matthiaskoenig/sbmlsim
          - text: Report a Bug
            href: https://github.com/matthiaskoenig/sbmlsim/issues

  page-footer:
    left: "Copyright 2019-2026, Matthias König, [https://livermetabolism.com](https://livermetabolism.com)"
    right:
      - icon: github
        href: https://github.com/matthiaskoenig
      - icon: linkedin
        href: https://www.linkedin.com/in/matthias-koenig/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - api/_styles-quartodoc.css
    toc: true


# tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: sbmlsim

  # write sidebar and style data
  sidebar: api/_sidebar.yml
  css: api/_styles-quartodoc.css
  version: 0.3.0
  dir: api

  sections:
    - title: API sensitivity
      desc: Sensitivity functionality.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - name: sensitivity
        - name: sensitivity.sensitivity_local
        - name: sensitivity.sensitivity_fast
        - name: sensitivity.sensitivity_sobol
        - name: sensitivity.sensitivity_morris
        - name: sensitivity.sensitivity_sampling

#filters:
#  - interlinks
#
#interlinks:
#  sources: {}
